app:
  build: .
  command: gin -a "9001" -p "9002"
  ports:
  - "9001:9001"
  - "9002:9002"
  volumes:
  - .:/code
  links:
  - mongo
  - redis
mongo:
  image: mongo:latest
redis:
  image: redis:latest